// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProntPet.Data;

#nullable disable

namespace ProntPet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521232337_CreateConsultationTable")]
    partial class CreateConsultationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProntPet.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("DB_CLINIC");
                });

            modelBuilder.Entity("ProntPet.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CONSULTATION_DATE");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DIAGNOSIS");

                    b.Property<int>("IdClinic")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINIC");

                    b.Property<int>("IdMedicalRecord")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MEDICAL_RECORD");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("OBSERVATIONS");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SYMPTOMS");

                    b.HasKey("Id");

                    b.HasIndex("IdClinic");

                    b.HasIndex("IdMedicalRecord");

                    b.ToTable("DB_CONSULTATION");
                });

            modelBuilder.Entity("ProntPet.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ALLERGIES");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)")
                        .HasColumnName("BLOOD_TYPE");

                    b.Property<string>("ChronicDiseases")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("CHRONIC_DISEASES");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PET");

                    b.Property<bool>("IsCastrated")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_CASTRATED");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<string>("MicrochipCode")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MICROCHIP_CODE");

                    b.HasKey("Id");

                    b.HasIndex("IdPet")
                        .IsUnique();

                    b.HasIndex("MicrochipCode")
                        .IsUnique()
                        .HasFilter("\"MICROCHIP_CODE\" IS NOT NULL");

                    b.ToTable("DB_MEDICAL_RECORD");
                });

            modelBuilder.Entity("ProntPet.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BIRTH_DATE");

                    b.Property<string>("Breed")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("BREED");

                    b.Property<int>("IdTutor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("SEX");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SPECIES");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("WEIGHT");

                    b.HasKey("Id");

                    b.HasIndex("IdTutor");

                    b.ToTable("DB_PET");
                });

            modelBuilder.Entity("ProntPet.Models.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("PHONE");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("DB_TUTOR");
                });

            modelBuilder.Entity("ProntPet.Models.Vaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("APPLICATION_DATE");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPIRATION_DATE");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("LOT");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("VACCINE_NAME");

                    b.HasKey("Id");

                    b.HasIndex("IdPet");

                    b.ToTable("DB_VACCINATION");
                });

            modelBuilder.Entity("ProntPet.Models.Consultation", b =>
                {
                    b.HasOne("ProntPet.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("IdClinic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProntPet.Models.MedicalRecord", "MedicalRecord")
                        .WithMany()
                        .HasForeignKey("IdMedicalRecord")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("ProntPet.Models.MedicalRecord", b =>
                {
                    b.HasOne("ProntPet.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("ProntPet.Models.Pet", b =>
                {
                    b.HasOne("ProntPet.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("ProntPet.Models.Vaccination", b =>
                {
                    b.HasOne("ProntPet.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });
#pragma warning restore 612, 618
        }
    }
}
